### ISSUE TITLE
Missing Defer Attribute in script tag

### ISSUE THREAD

**Issue by nickjoven** [learn-co-curriculum/phase-1-woof-woof-js-practice#2]
### Canvas Link

https://learning.flatironschool.com/courses/5206/assignments/191566?module_item_id=427718

### Concern

The script tag linking the JavaScript is located in the HTML's head tag. But, since there is no defer tag (or equivalent solution) when the browser attempts to run JavaScript code it will probably throw a 'reading properties of null' error.

![image](https://user-images.githubusercontent.com/106778049/179025524-ad7a690e-d219-4701-935c-dfb652b84c04.png)

### Suggested Changes

Add _defer_ to the script tag on line 7.

`    <script defer type="text/javascript" src="src/index.js"></script>`

**Comment by lizbur10** [comment]
Hi @nickjoven! Thanks for raising this issue! This is a good solution to the issue you've identified, but one of the expectations for the labs in this section is writing code to deal with this issue. As such, I'm going to leave the lab as is.

Thanks for contributing to the Flatiron School curriculum 💙
